print 'Episode      Episode Title    Release Date'
print '------- --------------------- ------------'
print 'IV      A New Hope                1977'
print 'V       The Empire Strikes Back   1980'
print 'VI      Return of the Jedi        1983'
print 'I       The Phantom Menace        1999'
print 'II      Attack of the Clones      2002'
print 'III     Revenge of the Sith       2005'
print 'VII     The Force Awakens         2015'
